version: "3"
services:
  app:
    build:
      context: ./app
      dockerfile: ./Dockerfile
    ports:
      - "18501:8501"
    command: streamlit run streamlit_app.py --server.port=8501 --server.address=0.0.0.0
    restart: always
